<?php

declare(strict_types=1);

namespace App\Demo;

final class VehicleFixtures
{
    /**
     * Deterministic by design - no randomness and no clock, for the same reason
     * DemoDashboard has none: tests assert on these values, and someone comparing
     * their own work against the demo needs it to look the same on every load.
     *
     * Returned insert-ready (plain scalars, no models), because the migration
     * inserts these rows with the query builder.
     *
     * @return list<array<string, mixed>>
     */
    public static function rows(): array
    {
        $rows = [];

        foreach (self::fleet() as $index => $vehicle) {
            $rows[] = [
                // Derived from the position so a hand-edited fixture can't
                // duplicate a stock number or leave a gap in the sequence.
                'stock_number' => sprintf('FL-%04d', 1000 + $index),
                // 11 fixed characters plus six digits is exactly the 17 a VIN has.
                'vin'          => sprintf('1HGBH41JXMN%06d', 109186 + $index),
                ...$vehicle,
            ];
        }

        return $rows;
    }

    /**
     * Everything that varies per vehicle. purchase_price is in cents.
     *
     * @return list<array<string, mixed>>
     */
    private static function fleet(): array
    {
        return [
            ['make' => 'Ford', 'model' => 'Transit 350', 'year' => 2022, 'color' => 'Oxford White', 'body_type' => 'van', 'fuel_type' => 'diesel', 'odometer' => 48210, 'status' => 'available', 'assigned_driver' => 'Priya Raman', 'bookable' => true, 'purchased_on' => '2022-03-14', 'last_serviced_on' => '2026-06-02', 'purchase_price' => 4289900, 'license_plate' => 'FLT-4021', 'notes' => null],
            ['make' => 'Ford', 'model' => 'F-150', 'year' => 2021, 'color' => 'Iconic Silver', 'body_type' => 'pickup', 'fuel_type' => 'petrol', 'odometer' => 61840, 'status' => 'in_service', 'assigned_driver' => 'Tom Achebe', 'bookable' => false, 'purchased_on' => '2021-07-08', 'last_serviced_on' => '2026-05-19', 'purchase_price' => 4715000, 'license_plate' => 'FLT-4022', 'notes' => 'Towing package fitted at purchase.'],
            ['make' => 'Toyota', 'model' => 'Corolla', 'year' => 2023, 'color' => 'Celestite Grey', 'body_type' => 'sedan', 'fuel_type' => 'hybrid', 'odometer' => 19420, 'status' => 'available', 'assigned_driver' => 'Sam Ellery', 'bookable' => true, 'purchased_on' => '2023-01-22', 'last_serviced_on' => '2026-07-11', 'purchase_price' => 2649500, 'license_plate' => 'FLT-4023', 'notes' => null],
            ['make' => 'Toyota', 'model' => 'RAV4', 'year' => 2022, 'color' => 'Blueprint', 'body_type' => 'suv', 'fuel_type' => 'hybrid', 'odometer' => 33970, 'status' => 'available', 'assigned_driver' => 'Dana Whitfield', 'bookable' => true, 'purchased_on' => '2022-09-30', 'last_serviced_on' => '2026-04-28', 'purchase_price' => 3389000, 'license_plate' => 'FLT-4024', 'notes' => null],
            ['make' => 'Honda', 'model' => 'Civic', 'year' => 2020, 'color' => 'Sonic Grey', 'body_type' => 'sedan', 'fuel_type' => 'petrol', 'odometer' => 78310, 'status' => 'in_maintenance', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2020-05-11', 'last_serviced_on' => '2026-08-14', 'purchase_price' => 2215000, 'license_plate' => 'FLT-4025', 'notes' => 'Awaiting a rear suspension part.'],
            ['make' => 'Honda', 'model' => 'CR-V', 'year' => 2023, 'color' => 'Platinum White', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 21105, 'status' => 'available', 'assigned_driver' => 'Marcus Cole', 'bookable' => true, 'purchased_on' => '2023-04-03', 'last_serviced_on' => '2026-06-25', 'purchase_price' => 3495000, 'license_plate' => 'FLT-4026', 'notes' => null],
            ['make' => 'Chevrolet', 'model' => 'Silverado 1500', 'year' => 2019, 'color' => 'Summit White', 'body_type' => 'pickup', 'fuel_type' => 'petrol', 'odometer' => 104880, 'status' => 'retired', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2019-02-19', 'last_serviced_on' => '2025-11-06', 'purchase_price' => 4102000, 'license_plate' => null, 'notes' => 'Retired past 100k miles; pending auction.'],
            ['make' => 'Chevrolet', 'model' => 'Bolt EUV', 'year' => 2023, 'color' => 'Bright Blue', 'body_type' => 'hatchback', 'fuel_type' => 'electric', 'odometer' => 14260, 'status' => 'available', 'assigned_driver' => 'Ines Okafor', 'bookable' => true, 'purchased_on' => '2023-06-17', 'last_serviced_on' => '2026-07-30', 'purchase_price' => 2879000, 'license_plate' => 'FLT-4028', 'notes' => null],
            ['make' => 'Nissan', 'model' => 'Leaf', 'year' => 2021, 'color' => 'Gun Metallic', 'body_type' => 'hatchback', 'fuel_type' => 'electric', 'odometer' => 42615, 'status' => 'in_service', 'assigned_driver' => 'Priya Raman', 'bookable' => false, 'purchased_on' => '2021-10-05', 'last_serviced_on' => '2026-03-12', 'purchase_price' => 2459000, 'license_plate' => 'FLT-4029', 'notes' => null],
            ['make' => 'Tesla', 'model' => 'Model 3', 'year' => 2022, 'color' => 'Pearl White', 'body_type' => 'sedan', 'fuel_type' => 'electric', 'odometer' => 37890, 'status' => 'available', 'assigned_driver' => 'Tom Achebe', 'bookable' => true, 'purchased_on' => '2022-11-28', 'last_serviced_on' => '2026-05-02', 'purchase_price' => 4499000, 'license_plate' => 'FLT-4030', 'notes' => null],
            ['make' => 'Ram', 'model' => 'ProMaster 2500', 'year' => 2021, 'color' => 'Bright White', 'body_type' => 'van', 'fuel_type' => 'diesel', 'odometer' => 69440, 'status' => 'in_service', 'assigned_driver' => 'Sam Ellery', 'bookable' => false, 'purchased_on' => '2021-04-16', 'last_serviced_on' => '2026-02-21', 'purchase_price' => 4025000, 'license_plate' => 'FLT-4031', 'notes' => 'Shelving fitted for the parts run.'],
            ['make' => 'Mercedes-Benz', 'model' => 'Sprinter 2500', 'year' => 2023, 'color' => 'Arctic White', 'body_type' => 'van', 'fuel_type' => 'diesel', 'odometer' => 26730, 'status' => 'available', 'assigned_driver' => 'Dana Whitfield', 'bookable' => true, 'purchased_on' => '2023-02-09', 'last_serviced_on' => '2026-08-01', 'purchase_price' => 5789000, 'license_plate' => 'FLT-4032', 'notes' => null],
            ['make' => 'Subaru', 'model' => 'Outback', 'year' => 2020, 'color' => 'Autumn Green', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 88250, 'status' => 'in_maintenance', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2020-08-24', 'last_serviced_on' => '2026-07-19', 'purchase_price' => 3029000, 'license_plate' => 'FLT-4033', 'notes' => 'Head gasket inspection booked.'],
            ['make' => 'Hyundai', 'model' => 'Ioniq 5', 'year' => 2023, 'color' => 'Cyber Grey', 'body_type' => 'suv', 'fuel_type' => 'electric', 'odometer' => 12980, 'status' => 'available', 'assigned_driver' => 'Marcus Cole', 'bookable' => true, 'purchased_on' => '2023-08-12', 'last_serviced_on' => '2026-08-22', 'purchase_price' => 4189000, 'license_plate' => 'FLT-4034', 'notes' => null],
            ['make' => 'Kia', 'model' => 'Sorento', 'year' => 2022, 'color' => 'Gravity Blue', 'body_type' => 'suv', 'fuel_type' => 'hybrid', 'odometer' => 40115, 'status' => 'available', 'assigned_driver' => 'Ines Okafor', 'bookable' => true, 'purchased_on' => '2022-06-06', 'last_serviced_on' => '2026-06-14', 'purchase_price' => 3612000, 'license_plate' => 'FLT-4035', 'notes' => null],
            ['make' => 'Toyota', 'model' => 'Prius', 'year' => 2019, 'color' => 'Sea Glass', 'body_type' => 'hatchback', 'fuel_type' => 'hybrid', 'odometer' => 96470, 'status' => 'retired', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2019-09-02', 'last_serviced_on' => '2025-12-18', 'purchase_price' => 2189000, 'license_plate' => null, 'notes' => 'Sold to a staff member, paperwork still open.'],
            ['make' => 'Ford', 'model' => 'Escape', 'year' => 2021, 'color' => 'Rapid Red', 'body_type' => 'suv', 'fuel_type' => 'hybrid', 'odometer' => 55320, 'status' => 'available', 'assigned_driver' => 'Priya Raman', 'bookable' => true, 'purchased_on' => '2021-12-01', 'last_serviced_on' => '2026-04-09', 'purchase_price' => 2949000, 'license_plate' => 'FLT-4037', 'notes' => null],
            ['make' => 'Volkswagen', 'model' => 'Golf', 'year' => 2020, 'color' => 'Deep Black', 'body_type' => 'hatchback', 'fuel_type' => 'petrol', 'odometer' => 71960, 'status' => 'in_service', 'assigned_driver' => 'Tom Achebe', 'bookable' => false, 'purchased_on' => '2020-03-27', 'last_serviced_on' => '2026-01-30', 'purchase_price' => 2375000, 'license_plate' => 'FLT-4038', 'notes' => null],
            ['make' => 'Mazda', 'model' => 'CX-5', 'year' => 2022, 'color' => 'Machine Grey', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 34840, 'status' => 'available', 'assigned_driver' => 'Sam Ellery', 'bookable' => true, 'purchased_on' => '2022-05-20', 'last_serviced_on' => '2026-05-27', 'purchase_price' => 3218000, 'license_plate' => 'FLT-4039', 'notes' => null],
            ['make' => 'GMC', 'model' => 'Sierra 1500', 'year' => 2021, 'color' => 'Onyx Black', 'body_type' => 'pickup', 'fuel_type' => 'diesel', 'odometer' => 62790, 'status' => 'available', 'assigned_driver' => 'Dana Whitfield', 'bookable' => true, 'purchased_on' => '2021-11-11', 'last_serviced_on' => '2026-03-05', 'purchase_price' => 5124000, 'license_plate' => 'FLT-4040', 'notes' => null],
            ['make' => 'Ford', 'model' => 'Transit Connect', 'year' => 2023, 'color' => 'Agate Black', 'body_type' => 'van', 'fuel_type' => 'petrol', 'odometer' => 17540, 'status' => 'available', 'assigned_driver' => null, 'bookable' => true, 'purchased_on' => '2023-03-30', 'last_serviced_on' => null, 'purchase_price' => 3082000, 'license_plate' => 'FLT-4041', 'notes' => 'Not yet serviced - still inside the first interval.'],
            ['make' => 'Toyota', 'model' => 'Camry', 'year' => 2021, 'color' => 'Predawn Grey', 'body_type' => 'sedan', 'fuel_type' => 'hybrid', 'odometer' => 51230, 'status' => 'in_service', 'assigned_driver' => 'Marcus Cole', 'bookable' => false, 'purchased_on' => '2021-06-23', 'last_serviced_on' => '2026-07-02', 'purchase_price' => 2891000, 'license_plate' => 'FLT-4042', 'notes' => null],
            ['make' => 'Honda', 'model' => 'Odyssey', 'year' => 2020, 'color' => 'Modern Steel', 'body_type' => 'van', 'fuel_type' => 'petrol', 'odometer' => 83610, 'status' => 'in_maintenance', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2020-10-14', 'last_serviced_on' => '2026-08-08', 'purchase_price' => 3395000, 'license_plate' => 'FLT-4043', 'notes' => 'Sliding door motor on order.'],
            ['make' => 'Nissan', 'model' => 'Frontier', 'year' => 2022, 'color' => 'Boulder Grey', 'body_type' => 'pickup', 'fuel_type' => 'petrol', 'odometer' => 44920, 'status' => 'available', 'assigned_driver' => 'Ines Okafor', 'bookable' => true, 'purchased_on' => '2022-08-18', 'last_serviced_on' => '2026-06-30', 'purchase_price' => 3671000, 'license_plate' => 'FLT-4044', 'notes' => null],
            ['make' => 'Tesla', 'model' => 'Model Y', 'year' => 2023, 'color' => 'Midnight Silver', 'body_type' => 'suv', 'fuel_type' => 'electric', 'odometer' => 22470, 'status' => 'available', 'assigned_driver' => 'Priya Raman', 'bookable' => true, 'purchased_on' => '2023-05-25', 'last_serviced_on' => '2026-08-16', 'purchase_price' => 5289000, 'license_plate' => 'FLT-4045', 'notes' => null],
            ['make' => 'Chevrolet', 'model' => 'Express 2500', 'year' => 2019, 'color' => 'Summit White', 'body_type' => 'van', 'fuel_type' => 'petrol', 'odometer' => 112340, 'status' => 'retired', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2019-01-15', 'last_serviced_on' => '2025-10-22', 'purchase_price' => 3488000, 'license_plate' => null, 'notes' => 'Awaiting collection by the buyer.'],
            ['make' => 'Hyundai', 'model' => 'Tucson', 'year' => 2022, 'color' => 'Amazon Grey', 'body_type' => 'suv', 'fuel_type' => 'hybrid', 'odometer' => 38650, 'status' => 'available', 'assigned_driver' => 'Tom Achebe', 'bookable' => true, 'purchased_on' => '2022-04-12', 'last_serviced_on' => '2026-05-14', 'purchase_price' => 3145000, 'license_plate' => 'FLT-4047', 'notes' => null],
            ['make' => 'Kia', 'model' => 'Niro', 'year' => 2021, 'color' => 'Snow White Pearl', 'body_type' => 'hatchback', 'fuel_type' => 'hybrid', 'odometer' => 47280, 'status' => 'available', 'assigned_driver' => 'Sam Ellery', 'bookable' => true, 'purchased_on' => '2021-09-07', 'last_serviced_on' => '2026-02-27', 'purchase_price' => 2698000, 'license_plate' => 'FLT-4048', 'notes' => null],
            ['make' => 'Subaru', 'model' => 'Forester', 'year' => 2023, 'color' => 'Cascade Green', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 15890, 'status' => 'available', 'assigned_driver' => 'Dana Whitfield', 'bookable' => true, 'purchased_on' => '2023-07-19', 'last_serviced_on' => '2026-07-25', 'purchase_price' => 3249000, 'license_plate' => 'FLT-4049', 'notes' => null],
            ['make' => 'Ford', 'model' => 'Ranger', 'year' => 2020, 'color' => 'Cactus Grey', 'body_type' => 'pickup', 'fuel_type' => 'diesel', 'odometer' => 79430, 'status' => 'in_service', 'assigned_driver' => 'Marcus Cole', 'bookable' => false, 'purchased_on' => '2020-06-29', 'last_serviced_on' => '2026-01-16', 'purchase_price' => 3419000, 'license_plate' => 'FLT-4050', 'notes' => null],
            ['make' => 'Volkswagen', 'model' => 'ID.4', 'year' => 2023, 'color' => 'Dusk Blue', 'body_type' => 'suv', 'fuel_type' => 'electric', 'odometer' => 11720, 'status' => 'available', 'assigned_driver' => 'Ines Okafor', 'bookable' => true, 'purchased_on' => '2023-09-05', 'last_serviced_on' => '2026-08-29', 'purchase_price' => 4059000, 'license_plate' => 'FLT-4051', 'notes' => null],
            ['make' => 'Mazda', 'model' => 'Mazda3', 'year' => 2021, 'color' => 'Polymetal Grey', 'body_type' => 'hatchback', 'fuel_type' => 'petrol', 'odometer' => 53170, 'status' => 'available', 'assigned_driver' => null, 'bookable' => true, 'purchased_on' => '2021-02-24', 'last_serviced_on' => '2026-04-17', 'purchase_price' => 2489000, 'license_plate' => 'FLT-4052', 'notes' => null],
            ['make' => 'Toyota', 'model' => 'Tacoma', 'year' => 2019, 'color' => 'Magnetic Grey', 'body_type' => 'pickup', 'fuel_type' => 'petrol', 'odometer' => 99850, 'status' => 'in_maintenance', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2019-11-20', 'last_serviced_on' => '2026-06-11', 'purchase_price' => 3789000, 'license_plate' => 'FLT-4053', 'notes' => 'Frame corrosion inspection.'],
            ['make' => 'Honda', 'model' => 'Accord', 'year' => 2022, 'color' => 'Canyon River Blue', 'body_type' => 'sedan', 'fuel_type' => 'hybrid', 'odometer' => 41360, 'status' => 'available', 'assigned_driver' => 'Priya Raman', 'bookable' => true, 'purchased_on' => '2022-01-31', 'last_serviced_on' => '2026-03-24', 'purchase_price' => 3195000, 'license_plate' => 'FLT-4054', 'notes' => null],
            ['make' => 'Nissan', 'model' => 'NV200', 'year' => 2020, 'color' => 'Fresh Powder', 'body_type' => 'van', 'fuel_type' => 'petrol', 'odometer' => 85940, 'status' => 'retired', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2020-02-06', 'last_serviced_on' => '2025-09-30', 'purchase_price' => 2589000, 'license_plate' => null, 'notes' => null],
            ['make' => 'Mercedes-Benz', 'model' => 'Metris', 'year' => 2022, 'color' => 'Jupiter Red', 'body_type' => 'van', 'fuel_type' => 'petrol', 'odometer' => 36280, 'status' => 'available', 'assigned_driver' => 'Tom Achebe', 'bookable' => true, 'purchased_on' => '2022-10-21', 'last_serviced_on' => '2026-07-08', 'purchase_price' => 4318000, 'license_plate' => 'FLT-4056', 'notes' => null],
            ['make' => 'Hyundai', 'model' => 'Elantra', 'year' => 2023, 'color' => 'Fluid Metal', 'body_type' => 'sedan', 'fuel_type' => 'petrol', 'odometer' => 18630, 'status' => 'available', 'assigned_driver' => 'Sam Ellery', 'bookable' => true, 'purchased_on' => '2023-04-27', 'last_serviced_on' => '2026-08-05', 'purchase_price' => 2298000, 'license_plate' => 'FLT-4057', 'notes' => null],
            ['make' => 'Kia', 'model' => 'EV6', 'year' => 2023, 'color' => 'Runway Red', 'body_type' => 'suv', 'fuel_type' => 'electric', 'odometer' => 13450, 'status' => 'in_service', 'assigned_driver' => 'Dana Whitfield', 'bookable' => false, 'purchased_on' => '2023-10-13', 'last_serviced_on' => '2026-08-19', 'purchase_price' => 4879000, 'license_plate' => 'FLT-4058', 'notes' => null],
            ['make' => 'Chevrolet', 'model' => 'Equinox', 'year' => 2021, 'color' => 'Mosaic Black', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 58720, 'status' => 'available', 'assigned_driver' => 'Marcus Cole', 'bookable' => true, 'purchased_on' => '2021-05-18', 'last_serviced_on' => '2026-05-06', 'purchase_price' => 2879000, 'license_plate' => 'FLT-4059', 'notes' => null],
            ['make' => 'Ford', 'model' => 'Maverick', 'year' => 2022, 'color' => 'Area 51', 'body_type' => 'pickup', 'fuel_type' => 'hybrid', 'odometer' => 29360, 'status' => 'available', 'assigned_driver' => 'Ines Okafor', 'bookable' => true, 'purchased_on' => '2022-07-14', 'last_serviced_on' => '2026-06-18', 'purchase_price' => 2949000, 'license_plate' => 'FLT-4060', 'notes' => null],
            ['make' => 'Toyota', 'model' => 'Sienna', 'year' => 2021, 'color' => 'Celestial Silver', 'body_type' => 'van', 'fuel_type' => 'hybrid', 'odometer' => 60480, 'status' => 'available', 'assigned_driver' => null, 'bookable' => true, 'purchased_on' => '2021-08-02', 'last_serviced_on' => '2026-04-22', 'purchase_price' => 4229000, 'license_plate' => 'FLT-4061', 'notes' => null],
            ['make' => 'Subaru', 'model' => 'Crosstrek', 'year' => 2020, 'color' => 'Plasma Yellow', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 74510, 'status' => 'in_service', 'assigned_driver' => 'Priya Raman', 'bookable' => false, 'purchased_on' => '2020-12-09', 'last_serviced_on' => '2026-02-13', 'purchase_price' => 2749000, 'license_plate' => 'FLT-4062', 'notes' => null],
            ['make' => 'Volkswagen', 'model' => 'Atlas', 'year' => 2022, 'color' => 'Aurora Red', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 45830, 'status' => 'available', 'assigned_driver' => 'Tom Achebe', 'bookable' => true, 'purchased_on' => '2022-02-17', 'last_serviced_on' => '2026-07-16', 'purchase_price' => 3898000, 'license_plate' => 'FLT-4063', 'notes' => null],
            ['make' => 'Mazda', 'model' => 'CX-9', 'year' => 2019, 'color' => 'Snowflake White', 'body_type' => 'suv', 'fuel_type' => 'petrol', 'odometer' => 101270, 'status' => 'retired', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2019-06-11', 'last_serviced_on' => '2025-11-27', 'purchase_price' => 3629000, 'license_plate' => null, 'notes' => 'Replaced by FL-1043.'],
            ['make' => 'Tesla', 'model' => 'Model Y', 'year' => 2024, 'color' => 'Quicksilver', 'body_type' => 'suv', 'fuel_type' => 'electric', 'odometer' => 6820, 'status' => 'in_maintenance', 'assigned_driver' => null, 'bookable' => false, 'purchased_on' => '2024-01-09', 'last_serviced_on' => '2026-08-26', 'purchase_price' => 5489000, 'license_plate' => 'FLT-4065', 'notes' => 'Software recall applied; awaiting a road test.'],
        ];
    }
}
